#!/bin/bash
# Copyright 2011 Karl-Michael Schneider
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

function is_cygwin() {
    eval "cygpath -w /" > /dev/null 2>&1
}

scriptpath=`readlink -f "$0"`
scriptdir="${scriptpath%/*}"
projectdir="${scriptdir%/*}"
propertiesfile="$projectdir/resources/toolkit.properties"

# Use this if you compile class files in eclipse:
#CLASSDIR="$projectdir/../bin"
# Use this if you compile class files with ant:
CLASSDIR="$projectdir/build/classes/framework"
JARDIR="$projectdir/lib"
JAVA=java

CLASSPATH="$CLASSDIR"

JARS=`find $JARDIR -type f -name \*.jar`
JARS=`echo $JARS`
CLASSPATH="$CLASSPATH:${JARS// /:}"

if is_cygwin; then
    CLASSPATH=`cygpath -mp "$CLASSPATH"`
fi

"$JAVA" -cp "$CLASSPATH" -Dtoolkit.properties="$propertiesfile" org.jwatter.toolkit.Toolkit "$@"
